/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellMediaRouteImport } from './routes/_shell.media'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScheduleRouteImport } from './routes/_shell.schedule'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ApiPublicConfigRouteImport } from './routes/api.public-config'
import { Route as ApiBrandingRouteImport } from './routes/api.branding'
import { Route as ApiAuthLoginAttemptRouteImport } from './routes/api.auth.login-attempt'
import { Route as ShellCampaignsIndexRouteImport } from './routes/_shell.campaigns.index'
import { Route as ShellCampaignsIdRouteImport } from './routes/_shell.campaigns.$id'
import { Route as ShellCampaignsNewRouteImport } from './routes/_shell.campaigns.new'
import { Route as ShellLayoutsIndexRouteImport } from './routes/_shell.layouts.index'
import { Route as ShellLayoutsIdRouteImport } from './routes/_shell.layouts.$id'
import { Route as ShellLayoutsNewRouteImport } from './routes/_shell.layouts.new'
import { Route as ShellLocationsIndexRouteImport } from './routes/_shell.locations.index'
import { Route as ShellLocationsIdRouteImport } from './routes/_shell.locations.$id'
import { Route as ShellPlaylistsIndexRouteImport } from './routes/_shell.playlists.index'
import { Route as ShellPlaylistsIdRouteImport } from './routes/_shell.playlists.$id'
import { Route as ShellPlaylistsNewRouteImport } from './routes/_shell.playlists.new'
import { Route as ShellScreensIndexRouteImport } from './routes/_shell.screens.index'
import { Route as ShellScreensIdRouteImport } from './routes/_shell.screens.$id'
import { Route as ApiDevicesActivateRouteImport } from './routes/api.devices.activate'
import { Route as ApiDevicesPairRouteImport } from './routes/api.devices.pair'
import { Route as ApiDevicesPlayerBrandingRouteImport } from './routes/api.devices.player-branding'
import { Route as ApiDevicesDeviceIdErrorLogsRouteImport } from './routes/api.devices.$deviceId.error-logs'
import { Route as ApiDevicesDeviceIdHeartbeatRouteImport } from './routes/api.devices.$deviceId.heartbeat'
import { Route as ApiDevicesDeviceIdManifestRouteImport } from './routes/api.devices.$deviceId.manifest'
import { Route as ApiDevicesDeviceIdPlaybackLogsRouteImport } from './routes/api.devices.$deviceId.playback-logs'
import { Route as ApiDevicesDeviceIdSyncConfirmationRouteImport } from './routes/api.devices.$deviceId.sync-confirmation'
import { Route as ApiDevicesDeviceIdSyncStatusRouteImport } from './routes/api.devices.$deviceId.sync-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMediaRoute = ShellMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScheduleRoute = ShellScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public-config',
  path: '/api/public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingRoute = ApiBrandingRouteImport.update({
  id: '/api/branding',
  path: '/api/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginAttemptRoute = ApiAuthLoginAttemptRouteImport.update({
  id: '/api/auth/login-attempt',
  path: '/api/auth/login-attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCampaignsIndexRoute = ShellCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsIdRoute = ShellCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsNewRoute = ShellCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsIndexRoute = ShellLayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsIdRoute = ShellLayoutsIdRouteImport.update({
  id: '/layouts/$id',
  path: '/layouts/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsNewRoute = ShellLayoutsNewRouteImport.update({
  id: '/layouts/new',
  path: '/layouts/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLocationsIndexRoute = ShellLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLocationsIdRoute = ShellLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsIndexRoute = ShellPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsIdRoute = ShellPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsNewRoute = ShellPlaylistsNewRouteImport.update({
  id: '/playlists/new',
  path: '/playlists/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScreensIndexRoute = ShellScreensIndexRouteImport.update({
  id: '/screens/',
  path: '/screens/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScreensIdRoute = ShellScreensIdRouteImport.update({
  id: '/screens/$id',
  path: '/screens/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ApiDevicesActivateRoute = ApiDevicesActivateRouteImport.update({
  id: '/api/devices/activate',
  path: '/api/devices/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesPairRoute = ApiDevicesPairRouteImport.update({
  id: '/api/devices/pair',
  path: '/api/devices/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesPlayerBrandingRoute = ApiDevicesPlayerBrandingRouteImport.update({
  id: '/api/devices/player-branding',
  path: '/api/devices/player-branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesDeviceIdErrorLogsRoute =
  ApiDevicesDeviceIdErrorLogsRouteImport.update({
    id: '/api/devices/$deviceId/error-logs',
    path: '/api/devices/$deviceId/error-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesDeviceIdHeartbeatRoute =
  ApiDevicesDeviceIdHeartbeatRouteImport.update({
    id: '/api/devices/$deviceId/heartbeat',
    path: '/api/devices/$deviceId/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesDeviceIdManifestRoute =
  ApiDevicesDeviceIdManifestRouteImport.update({
    id: '/api/devices/$deviceId/manifest',
    path: '/api/devices/$deviceId/manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesDeviceIdPlaybackLogsRoute =
  ApiDevicesDeviceIdPlaybackLogsRouteImport.update({
    id: '/api/devices/$deviceId/playback-logs',
    path: '/api/devices/$deviceId/playback-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesDeviceIdSyncConfirmationRoute =
  ApiDevicesDeviceIdSyncConfirmationRouteImport.update({
    id: '/api/devices/$deviceId/sync-confirmation',
    path: '/api/devices/$deviceId/sync-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevicesDeviceIdSyncStatusRoute =
  ApiDevicesDeviceIdSyncStatusRouteImport.update({
    id: '/api/devices/$deviceId/sync-status',
    path: '/api/devices/$deviceId/sync-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/media': typeof ShellMediaRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/branding': typeof ApiBrandingRoute
  '/api/auth/login-attempt': typeof ApiAuthLoginAttemptRoute
  '/campaigns/$id': typeof ShellCampaignsIdRoute
  '/campaigns/new': typeof ShellCampaignsNewRoute
  '/layouts/$id': typeof ShellLayoutsIdRoute
  '/layouts/new': typeof ShellLayoutsNewRoute
  '/locations/$id': typeof ShellLocationsIdRoute
  '/playlists/$id': typeof ShellPlaylistsIdRoute
  '/playlists/new': typeof ShellPlaylistsNewRoute
  '/screens/$id': typeof ShellScreensIdRoute
  '/api/devices/activate': typeof ApiDevicesActivateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/player-branding': typeof ApiDevicesPlayerBrandingRoute
  '/campaigns/': typeof ShellCampaignsIndexRoute
  '/layouts/': typeof ShellLayoutsIndexRoute
  '/locations/': typeof ShellLocationsIndexRoute
  '/playlists/': typeof ShellPlaylistsIndexRoute
  '/screens/': typeof ShellScreensIndexRoute
  '/api/devices/$deviceId/error-logs': typeof ApiDevicesDeviceIdErrorLogsRoute
  '/api/devices/$deviceId/heartbeat': typeof ApiDevicesDeviceIdHeartbeatRoute
  '/api/devices/$deviceId/manifest': typeof ApiDevicesDeviceIdManifestRoute
  '/api/devices/$deviceId/playback-logs': typeof ApiDevicesDeviceIdPlaybackLogsRoute
  '/api/devices/$deviceId/sync-confirmation': typeof ApiDevicesDeviceIdSyncConfirmationRoute
  '/api/devices/$deviceId/sync-status': typeof ApiDevicesDeviceIdSyncStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/media': typeof ShellMediaRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/branding': typeof ApiBrandingRoute
  '/api/auth/login-attempt': typeof ApiAuthLoginAttemptRoute
  '/campaigns/$id': typeof ShellCampaignsIdRoute
  '/campaigns/new': typeof ShellCampaignsNewRoute
  '/layouts/$id': typeof ShellLayoutsIdRoute
  '/layouts/new': typeof ShellLayoutsNewRoute
  '/locations/$id': typeof ShellLocationsIdRoute
  '/playlists/$id': typeof ShellPlaylistsIdRoute
  '/playlists/new': typeof ShellPlaylistsNewRoute
  '/screens/$id': typeof ShellScreensIdRoute
  '/api/devices/activate': typeof ApiDevicesActivateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/player-branding': typeof ApiDevicesPlayerBrandingRoute
  '/campaigns': typeof ShellCampaignsIndexRoute
  '/layouts': typeof ShellLayoutsIndexRoute
  '/locations': typeof ShellLocationsIndexRoute
  '/playlists': typeof ShellPlaylistsIndexRoute
  '/screens': typeof ShellScreensIndexRoute
  '/api/devices/$deviceId/error-logs': typeof ApiDevicesDeviceIdErrorLogsRoute
  '/api/devices/$deviceId/heartbeat': typeof ApiDevicesDeviceIdHeartbeatRoute
  '/api/devices/$deviceId/manifest': typeof ApiDevicesDeviceIdManifestRoute
  '/api/devices/$deviceId/playback-logs': typeof ApiDevicesDeviceIdPlaybackLogsRoute
  '/api/devices/$deviceId/sync-confirmation': typeof ApiDevicesDeviceIdSyncConfirmationRoute
  '/api/devices/$deviceId/sync-status': typeof ApiDevicesDeviceIdSyncStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/media': typeof ShellMediaRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/schedule': typeof ShellScheduleRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/api/public-config': typeof ApiPublicConfigRoute
  '/api/branding': typeof ApiBrandingRoute
  '/api/auth/login-attempt': typeof ApiAuthLoginAttemptRoute
  '/_shell/campaigns/$id': typeof ShellCampaignsIdRoute
  '/_shell/campaigns/new': typeof ShellCampaignsNewRoute
  '/_shell/layouts/$id': typeof ShellLayoutsIdRoute
  '/_shell/layouts/new': typeof ShellLayoutsNewRoute
  '/_shell/locations/$id': typeof ShellLocationsIdRoute
  '/_shell/playlists/$id': typeof ShellPlaylistsIdRoute
  '/_shell/playlists/new': typeof ShellPlaylistsNewRoute
  '/_shell/screens/$id': typeof ShellScreensIdRoute
  '/api/devices/activate': typeof ApiDevicesActivateRoute
  '/api/devices/pair': typeof ApiDevicesPairRoute
  '/api/devices/player-branding': typeof ApiDevicesPlayerBrandingRoute
  '/_shell/campaigns/': typeof ShellCampaignsIndexRoute
  '/_shell/layouts/': typeof ShellLayoutsIndexRoute
  '/_shell/locations/': typeof ShellLocationsIndexRoute
  '/_shell/playlists/': typeof ShellPlaylistsIndexRoute
  '/_shell/screens/': typeof ShellScreensIndexRoute
  '/api/devices/$deviceId/error-logs': typeof ApiDevicesDeviceIdErrorLogsRoute
  '/api/devices/$deviceId/heartbeat': typeof ApiDevicesDeviceIdHeartbeatRoute
  '/api/devices/$deviceId/manifest': typeof ApiDevicesDeviceIdManifestRoute
  '/api/devices/$deviceId/playback-logs': typeof ApiDevicesDeviceIdPlaybackLogsRoute
  '/api/devices/$deviceId/sync-confirmation': typeof ApiDevicesDeviceIdSyncConfirmationRoute
  '/api/devices/$deviceId/sync-status': typeof ApiDevicesDeviceIdSyncStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/media'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/api/public-config'
    | '/api/branding'
    | '/api/auth/login-attempt'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/layouts/$id'
    | '/layouts/new'
    | '/locations/$id'
    | '/playlists/$id'
    | '/playlists/new'
    | '/screens/$id'
    | '/api/devices/activate'
    | '/api/devices/pair'
    | '/api/devices/player-branding'
    | '/campaigns/'
    | '/layouts/'
    | '/locations/'
    | '/playlists/'
    | '/screens/'
    | '/api/devices/$deviceId/error-logs'
    | '/api/devices/$deviceId/heartbeat'
    | '/api/devices/$deviceId/manifest'
    | '/api/devices/$deviceId/playback-logs'
    | '/api/devices/$deviceId/sync-confirmation'
    | '/api/devices/$deviceId/sync-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/media'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/api/public-config'
    | '/api/branding'
    | '/api/auth/login-attempt'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/layouts/$id'
    | '/layouts/new'
    | '/locations/$id'
    | '/playlists/$id'
    | '/playlists/new'
    | '/screens/$id'
    | '/api/devices/activate'
    | '/api/devices/pair'
    | '/api/devices/player-branding'
    | '/campaigns'
    | '/layouts'
    | '/locations'
    | '/playlists'
    | '/screens'
    | '/api/devices/$deviceId/error-logs'
    | '/api/devices/$deviceId/heartbeat'
    | '/api/devices/$deviceId/manifest'
    | '/api/devices/$deviceId/playback-logs'
    | '/api/devices/$deviceId/sync-confirmation'
    | '/api/devices/$deviceId/sync-status'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/dashboard'
    | '/_shell/media'
    | '/_shell/reports'
    | '/_shell/schedule'
    | '/_shell/settings'
    | '/_shell/users'
    | '/api/public-config'
    | '/api/branding'
    | '/api/auth/login-attempt'
    | '/_shell/campaigns/$id'
    | '/_shell/campaigns/new'
    | '/_shell/layouts/$id'
    | '/_shell/layouts/new'
    | '/_shell/locations/$id'
    | '/_shell/playlists/$id'
    | '/_shell/playlists/new'
    | '/_shell/screens/$id'
    | '/api/devices/activate'
    | '/api/devices/pair'
    | '/api/devices/player-branding'
    | '/_shell/campaigns/'
    | '/_shell/layouts/'
    | '/_shell/locations/'
    | '/_shell/playlists/'
    | '/_shell/screens/'
    | '/api/devices/$deviceId/error-logs'
    | '/api/devices/$deviceId/heartbeat'
    | '/api/devices/$deviceId/manifest'
    | '/api/devices/$deviceId/playback-logs'
    | '/api/devices/$deviceId/sync-confirmation'
    | '/api/devices/$deviceId/sync-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiBrandingRoute: typeof ApiBrandingRoute
  ApiAuthLoginAttemptRoute: typeof ApiAuthLoginAttemptRoute
  ApiDevicesActivateRoute: typeof ApiDevicesActivateRoute
  ApiDevicesPairRoute: typeof ApiDevicesPairRoute
  ApiDevicesPlayerBrandingRoute: typeof ApiDevicesPlayerBrandingRoute
  ApiDevicesDeviceIdErrorLogsRoute: typeof ApiDevicesDeviceIdErrorLogsRoute
  ApiDevicesDeviceIdHeartbeatRoute: typeof ApiDevicesDeviceIdHeartbeatRoute
  ApiDevicesDeviceIdManifestRoute: typeof ApiDevicesDeviceIdManifestRoute
  ApiDevicesDeviceIdPlaybackLogsRoute: typeof ApiDevicesDeviceIdPlaybackLogsRoute
  ApiDevicesDeviceIdSyncConfirmationRoute: typeof ApiDevicesDeviceIdSyncConfirmationRoute
  ApiDevicesDeviceIdSyncStatusRoute: typeof ApiDevicesDeviceIdSyncStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/media': {
      id: '/_shell/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof ShellMediaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedule': {
      id: '/_shell/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ShellScheduleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public-config': {
      id: '/api/public-config'
      path: '/api/public-config'
      fullPath: '/api/public-config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding': {
      id: '/api/branding'
      path: '/api/branding'
      fullPath: '/api/branding'
      preLoaderRoute: typeof ApiBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login-attempt': {
      id: '/api/auth/login-attempt'
      path: '/api/auth/login-attempt'
      fullPath: '/api/auth/login-attempt'
      preLoaderRoute: typeof ApiAuthLoginAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/campaigns/': {
      id: '/_shell/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof ShellCampaignsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns/$id': {
      id: '/_shell/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof ShellCampaignsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns/new': {
      id: '/_shell/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof ShellCampaignsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/': {
      id: '/_shell/layouts/'
      path: '/layouts'
      fullPath: '/layouts/'
      preLoaderRoute: typeof ShellLayoutsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/$id': {
      id: '/_shell/layouts/$id'
      path: '/layouts/$id'
      fullPath: '/layouts/$id'
      preLoaderRoute: typeof ShellLayoutsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/new': {
      id: '/_shell/layouts/new'
      path: '/layouts/new'
      fullPath: '/layouts/new'
      preLoaderRoute: typeof ShellLayoutsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/locations/': {
      id: '/_shell/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof ShellLocationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/locations/$id': {
      id: '/_shell/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof ShellLocationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/': {
      id: '/_shell/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof ShellPlaylistsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/$id': {
      id: '/_shell/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof ShellPlaylistsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/new': {
      id: '/_shell/playlists/new'
      path: '/playlists/new'
      fullPath: '/playlists/new'
      preLoaderRoute: typeof ShellPlaylistsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/screens/': {
      id: '/_shell/screens/'
      path: '/screens'
      fullPath: '/screens/'
      preLoaderRoute: typeof ShellScreensIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/screens/$id': {
      id: '/_shell/screens/$id'
      path: '/screens/$id'
      fullPath: '/screens/$id'
      preLoaderRoute: typeof ShellScreensIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/devices/activate': {
      id: '/api/devices/activate'
      path: '/api/devices/activate'
      fullPath: '/api/devices/activate'
      preLoaderRoute: typeof ApiDevicesActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/pair': {
      id: '/api/devices/pair'
      path: '/api/devices/pair'
      fullPath: '/api/devices/pair'
      preLoaderRoute: typeof ApiDevicesPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/player-branding': {
      id: '/api/devices/player-branding'
      path: '/api/devices/player-branding'
      fullPath: '/api/devices/player-branding'
      preLoaderRoute: typeof ApiDevicesPlayerBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/error-logs': {
      id: '/api/devices/$deviceId/error-logs'
      path: '/api/devices/$deviceId/error-logs'
      fullPath: '/api/devices/$deviceId/error-logs'
      preLoaderRoute: typeof ApiDevicesDeviceIdErrorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/heartbeat': {
      id: '/api/devices/$deviceId/heartbeat'
      path: '/api/devices/$deviceId/heartbeat'
      fullPath: '/api/devices/$deviceId/heartbeat'
      preLoaderRoute: typeof ApiDevicesDeviceIdHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/manifest': {
      id: '/api/devices/$deviceId/manifest'
      path: '/api/devices/$deviceId/manifest'
      fullPath: '/api/devices/$deviceId/manifest'
      preLoaderRoute: typeof ApiDevicesDeviceIdManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/playback-logs': {
      id: '/api/devices/$deviceId/playback-logs'
      path: '/api/devices/$deviceId/playback-logs'
      fullPath: '/api/devices/$deviceId/playback-logs'
      preLoaderRoute: typeof ApiDevicesDeviceIdPlaybackLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/sync-confirmation': {
      id: '/api/devices/$deviceId/sync-confirmation'
      path: '/api/devices/$deviceId/sync-confirmation'
      fullPath: '/api/devices/$deviceId/sync-confirmation'
      preLoaderRoute: typeof ApiDevicesDeviceIdSyncConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$deviceId/sync-status': {
      id: '/api/devices/$deviceId/sync-status'
      path: '/api/devices/$deviceId/sync-status'
      fullPath: '/api/devices/$deviceId/sync-status'
      preLoaderRoute: typeof ApiDevicesDeviceIdSyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellMediaRoute: typeof ShellMediaRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScheduleRoute: typeof ShellScheduleRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellCampaignsIdRoute: typeof ShellCampaignsIdRoute
  ShellCampaignsNewRoute: typeof ShellCampaignsNewRoute
  ShellLayoutsIdRoute: typeof ShellLayoutsIdRoute
  ShellLayoutsNewRoute: typeof ShellLayoutsNewRoute
  ShellLocationsIdRoute: typeof ShellLocationsIdRoute
  ShellPlaylistsIdRoute: typeof ShellPlaylistsIdRoute
  ShellPlaylistsNewRoute: typeof ShellPlaylistsNewRoute
  ShellScreensIdRoute: typeof ShellScreensIdRoute
  ShellCampaignsIndexRoute: typeof ShellCampaignsIndexRoute
  ShellLayoutsIndexRoute: typeof ShellLayoutsIndexRoute
  ShellLocationsIndexRoute: typeof ShellLocationsIndexRoute
  ShellPlaylistsIndexRoute: typeof ShellPlaylistsIndexRoute
  ShellScreensIndexRoute: typeof ShellScreensIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellMediaRoute: ShellMediaRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScheduleRoute: ShellScheduleRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellCampaignsIdRoute: ShellCampaignsIdRoute,
  ShellCampaignsNewRoute: ShellCampaignsNewRoute,
  ShellLayoutsIdRoute: ShellLayoutsIdRoute,
  ShellLayoutsNewRoute: ShellLayoutsNewRoute,
  ShellLocationsIdRoute: ShellLocationsIdRoute,
  ShellPlaylistsIdRoute: ShellPlaylistsIdRoute,
  ShellPlaylistsNewRoute: ShellPlaylistsNewRoute,
  ShellScreensIdRoute: ShellScreensIdRoute,
  ShellCampaignsIndexRoute: ShellCampaignsIndexRoute,
  ShellLayoutsIndexRoute: ShellLayoutsIndexRoute,
  ShellLocationsIndexRoute: ShellLocationsIndexRoute,
  ShellPlaylistsIndexRoute: ShellPlaylistsIndexRoute,
  ShellScreensIndexRoute: ShellScreensIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiBrandingRoute: ApiBrandingRoute,
  ApiAuthLoginAttemptRoute: ApiAuthLoginAttemptRoute,
  ApiDevicesActivateRoute: ApiDevicesActivateRoute,
  ApiDevicesPairRoute: ApiDevicesPairRoute,
  ApiDevicesPlayerBrandingRoute: ApiDevicesPlayerBrandingRoute,
  ApiDevicesDeviceIdErrorLogsRoute: ApiDevicesDeviceIdErrorLogsRoute,
  ApiDevicesDeviceIdHeartbeatRoute: ApiDevicesDeviceIdHeartbeatRoute,
  ApiDevicesDeviceIdManifestRoute: ApiDevicesDeviceIdManifestRoute,
  ApiDevicesDeviceIdPlaybackLogsRoute: ApiDevicesDeviceIdPlaybackLogsRoute,
  ApiDevicesDeviceIdSyncConfirmationRoute:
    ApiDevicesDeviceIdSyncConfirmationRoute,
  ApiDevicesDeviceIdSyncStatusRoute: ApiDevicesDeviceIdSyncStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
