/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellMediaRouteImport } from './routes/_shell.media'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScheduleRouteImport } from './routes/_shell.schedule'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellCampaignsIndexRouteImport } from './routes/_shell.campaigns.index'
import { Route as ShellCampaignsIdRouteImport } from './routes/_shell.campaigns.$id'
import { Route as ShellCampaignsNewRouteImport } from './routes/_shell.campaigns.new'
import { Route as ShellLayoutsIndexRouteImport } from './routes/_shell.layouts.index'
import { Route as ShellLayoutsIdRouteImport } from './routes/_shell.layouts.$id'
import { Route as ShellLayoutsNewRouteImport } from './routes/_shell.layouts.new'
import { Route as ShellLocationsIndexRouteImport } from './routes/_shell.locations.index'
import { Route as ShellLocationsIdRouteImport } from './routes/_shell.locations.$id'
import { Route as ShellPlaylistsIndexRouteImport } from './routes/_shell.playlists.index'
import { Route as ShellPlaylistsIdRouteImport } from './routes/_shell.playlists.$id'
import { Route as ShellPlaylistsNewRouteImport } from './routes/_shell.playlists.new'
import { Route as ShellScreensIndexRouteImport } from './routes/_shell.screens.index'
import { Route as ShellScreensIdRouteImport } from './routes/_shell.screens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMediaRoute = ShellMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScheduleRoute = ShellScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsIndexRoute = ShellCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsIdRoute = ShellCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCampaignsNewRoute = ShellCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsIndexRoute = ShellLayoutsIndexRouteImport.update({
  id: '/layouts/',
  path: '/layouts/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsIdRoute = ShellLayoutsIdRouteImport.update({
  id: '/layouts/$id',
  path: '/layouts/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLayoutsNewRoute = ShellLayoutsNewRouteImport.update({
  id: '/layouts/new',
  path: '/layouts/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLocationsIndexRoute = ShellLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLocationsIdRoute = ShellLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsIndexRoute = ShellPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsIdRoute = ShellPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaylistsNewRoute = ShellPlaylistsNewRouteImport.update({
  id: '/playlists/new',
  path: '/playlists/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScreensIndexRoute = ShellScreensIndexRouteImport.update({
  id: '/screens/',
  path: '/screens/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScreensIdRoute = ShellScreensIdRouteImport.update({
  id: '/screens/$id',
  path: '/screens/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/media': typeof ShellMediaRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/campaigns/$id': typeof ShellCampaignsIdRoute
  '/campaigns/new': typeof ShellCampaignsNewRoute
  '/layouts/$id': typeof ShellLayoutsIdRoute
  '/layouts/new': typeof ShellLayoutsNewRoute
  '/locations/$id': typeof ShellLocationsIdRoute
  '/playlists/$id': typeof ShellPlaylistsIdRoute
  '/playlists/new': typeof ShellPlaylistsNewRoute
  '/screens/$id': typeof ShellScreensIdRoute
  '/campaigns/': typeof ShellCampaignsIndexRoute
  '/layouts/': typeof ShellLayoutsIndexRoute
  '/locations/': typeof ShellLocationsIndexRoute
  '/playlists/': typeof ShellPlaylistsIndexRoute
  '/screens/': typeof ShellScreensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ShellDashboardRoute
  '/media': typeof ShellMediaRoute
  '/reports': typeof ShellReportsRoute
  '/schedule': typeof ShellScheduleRoute
  '/settings': typeof ShellSettingsRoute
  '/users': typeof ShellUsersRoute
  '/campaigns/$id': typeof ShellCampaignsIdRoute
  '/campaigns/new': typeof ShellCampaignsNewRoute
  '/layouts/$id': typeof ShellLayoutsIdRoute
  '/layouts/new': typeof ShellLayoutsNewRoute
  '/locations/$id': typeof ShellLocationsIdRoute
  '/playlists/$id': typeof ShellPlaylistsIdRoute
  '/playlists/new': typeof ShellPlaylistsNewRoute
  '/screens/$id': typeof ShellScreensIdRoute
  '/campaigns': typeof ShellCampaignsIndexRoute
  '/layouts': typeof ShellLayoutsIndexRoute
  '/locations': typeof ShellLocationsIndexRoute
  '/playlists': typeof ShellPlaylistsIndexRoute
  '/screens': typeof ShellScreensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/media': typeof ShellMediaRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/schedule': typeof ShellScheduleRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/campaigns/$id': typeof ShellCampaignsIdRoute
  '/_shell/campaigns/new': typeof ShellCampaignsNewRoute
  '/_shell/layouts/$id': typeof ShellLayoutsIdRoute
  '/_shell/layouts/new': typeof ShellLayoutsNewRoute
  '/_shell/locations/$id': typeof ShellLocationsIdRoute
  '/_shell/playlists/$id': typeof ShellPlaylistsIdRoute
  '/_shell/playlists/new': typeof ShellPlaylistsNewRoute
  '/_shell/screens/$id': typeof ShellScreensIdRoute
  '/_shell/campaigns/': typeof ShellCampaignsIndexRoute
  '/_shell/layouts/': typeof ShellLayoutsIndexRoute
  '/_shell/locations/': typeof ShellLocationsIndexRoute
  '/_shell/playlists/': typeof ShellPlaylistsIndexRoute
  '/_shell/screens/': typeof ShellScreensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/media'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/layouts/$id'
    | '/layouts/new'
    | '/locations/$id'
    | '/playlists/$id'
    | '/playlists/new'
    | '/screens/$id'
    | '/campaigns/'
    | '/layouts/'
    | '/locations/'
    | '/playlists/'
    | '/screens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/media'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/users'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/layouts/$id'
    | '/layouts/new'
    | '/locations/$id'
    | '/playlists/$id'
    | '/playlists/new'
    | '/screens/$id'
    | '/campaigns'
    | '/layouts'
    | '/locations'
    | '/playlists'
    | '/screens'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/dashboard'
    | '/_shell/media'
    | '/_shell/reports'
    | '/_shell/schedule'
    | '/_shell/settings'
    | '/_shell/users'
    | '/_shell/campaigns/$id'
    | '/_shell/campaigns/new'
    | '/_shell/layouts/$id'
    | '/_shell/layouts/new'
    | '/_shell/locations/$id'
    | '/_shell/playlists/$id'
    | '/_shell/playlists/new'
    | '/_shell/screens/$id'
    | '/_shell/campaigns/'
    | '/_shell/layouts/'
    | '/_shell/locations/'
    | '/_shell/playlists/'
    | '/_shell/screens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/media': {
      id: '/_shell/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof ShellMediaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedule': {
      id: '/_shell/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ShellScheduleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns/': {
      id: '/_shell/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof ShellCampaignsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns/$id': {
      id: '/_shell/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof ShellCampaignsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/campaigns/new': {
      id: '/_shell/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof ShellCampaignsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/': {
      id: '/_shell/layouts/'
      path: '/layouts'
      fullPath: '/layouts/'
      preLoaderRoute: typeof ShellLayoutsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/$id': {
      id: '/_shell/layouts/$id'
      path: '/layouts/$id'
      fullPath: '/layouts/$id'
      preLoaderRoute: typeof ShellLayoutsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/layouts/new': {
      id: '/_shell/layouts/new'
      path: '/layouts/new'
      fullPath: '/layouts/new'
      preLoaderRoute: typeof ShellLayoutsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/locations/': {
      id: '/_shell/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof ShellLocationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/locations/$id': {
      id: '/_shell/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof ShellLocationsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/': {
      id: '/_shell/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof ShellPlaylistsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/$id': {
      id: '/_shell/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof ShellPlaylistsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playlists/new': {
      id: '/_shell/playlists/new'
      path: '/playlists/new'
      fullPath: '/playlists/new'
      preLoaderRoute: typeof ShellPlaylistsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/screens/': {
      id: '/_shell/screens/'
      path: '/screens'
      fullPath: '/screens/'
      preLoaderRoute: typeof ShellScreensIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/screens/$id': {
      id: '/_shell/screens/$id'
      path: '/screens/$id'
      fullPath: '/screens/$id'
      preLoaderRoute: typeof ShellScreensIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellMediaRoute: typeof ShellMediaRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScheduleRoute: typeof ShellScheduleRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellCampaignsIdRoute: typeof ShellCampaignsIdRoute
  ShellCampaignsNewRoute: typeof ShellCampaignsNewRoute
  ShellLayoutsIdRoute: typeof ShellLayoutsIdRoute
  ShellLayoutsNewRoute: typeof ShellLayoutsNewRoute
  ShellLocationsIdRoute: typeof ShellLocationsIdRoute
  ShellPlaylistsIdRoute: typeof ShellPlaylistsIdRoute
  ShellPlaylistsNewRoute: typeof ShellPlaylistsNewRoute
  ShellScreensIdRoute: typeof ShellScreensIdRoute
  ShellCampaignsIndexRoute: typeof ShellCampaignsIndexRoute
  ShellLayoutsIndexRoute: typeof ShellLayoutsIndexRoute
  ShellLocationsIndexRoute: typeof ShellLocationsIndexRoute
  ShellPlaylistsIndexRoute: typeof ShellPlaylistsIndexRoute
  ShellScreensIndexRoute: typeof ShellScreensIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellMediaRoute: ShellMediaRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScheduleRoute: ShellScheduleRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellCampaignsIdRoute: ShellCampaignsIdRoute,
  ShellCampaignsNewRoute: ShellCampaignsNewRoute,
  ShellLayoutsIdRoute: ShellLayoutsIdRoute,
  ShellLayoutsNewRoute: ShellLayoutsNewRoute,
  ShellLocationsIdRoute: ShellLocationsIdRoute,
  ShellPlaylistsIdRoute: ShellPlaylistsIdRoute,
  ShellPlaylistsNewRoute: ShellPlaylistsNewRoute,
  ShellScreensIdRoute: ShellScreensIdRoute,
  ShellCampaignsIndexRoute: ShellCampaignsIndexRoute,
  ShellLayoutsIndexRoute: ShellLayoutsIndexRoute,
  ShellLocationsIndexRoute: ShellLocationsIndexRoute,
  ShellPlaylistsIndexRoute: ShellPlaylistsIndexRoute,
  ShellScreensIndexRoute: ShellScreensIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
